################################### Spanish language #####################################
[es]
languageName = "es"
languageCode = "es-AR"
contentDir = "content/spanish"
weight = 1
[es.params]
home = "Inicio"
copyright = "Copyright &copy; 2025 Vivasa S.R.L. Todos los derechos reservados."

################################### English language #####################################
[en]
languageName = "en"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
[en.params]
home = "Home"
copyright = "Copyright &copy; 2025 Vivasa S.R.L. All rights reserved."

################################### French language #####################################
[fr]
languageName = "fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 3
[fr.params]
home = "Accueil"
copyright = "Copyright &copy; 2025 Vivasa S.R.L. Tous droits réservés."





