
################### English Navigation ########################
[[main]]
name = "acerca de"
url = "#about"
weight = 1

[[main]]
name = "servicios"
url = "#services"
weight = 2

[[main]]
name = "equipo"
url = "#team"
weight = 4

[[main]]
name = "contacto"
url = "#contact"
weight = 7
