
################### English Navigation ########################
[[main]]
name = "about"
url = "#about"
weight = 1

[[main]]
name = "services"
url = "#services"
weight = 2

[[main]]
name = "equipo"
url = "#team"
weight = 4

[[main]]
name = "contact"
url = "#contact"
weight = 7
